# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["jaskiratr@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = ""
language = "rust"
manifest_version = 3
name = "rust-resource-limit-test"
service_id = "jlC84LNSujxatPueHmZ6O5"

[scripts]
  build = "cargo build --bin fastly-compute-project --release --target wasm32-wasi --color always"
